// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Categories string
	Product    string
	Users      string
}{
	Categories: "categories",
	Product:    "product",
	Users:      "users",
}
