// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meetup struct {
	ID          string `json:"id"`
	Names       string `json:"names"`
	Description string `json:"description"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UpdateUser struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type User struct {
	ID       string    `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
	Meetups  []*Meetup `json:"meetups"`
}
